### ISSUE TITLE
hub restart crashes the script

### ISSUE THREAD

**Issue by andrei4002** [maddox/harmony-api#14] opened 2016-06-25 07:36 UTC
if I restart a harmony hub to which the harmony-api connected, it crashes and forever doesn't seem to restart the script, it just stays stuck. example log:

Connecting to Harmony hub at 192.169.1.152
Updating activities.
Updating state.
Updating state.
Updating state.
Updating state.
Updating state.
Updating state.
Updating state.
Updating state.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1007:11)
    at TCP.onread (net.js:563:26)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
Connecting to Harmony hub at 192.169.1.152
errorhub { Error: connect ECONNREFUSED 192.169.1.152:5222
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.169.1.152',
  port: 5222 }

**Comment by maddox** [comment] 2016-09-27 20:06
See if #19 fixes your problem. I just merged it. Pull down the newest version and see if it fixes it.

I think it might NOT fix it though, as I've been living on this branch for a while and I think a power cycle of my Harmony hub broke it the other night. Thanks for submitting this, as now I can actually reproduce why there was something happening.

It's most likely because discovery is stopping I bet. I'll dig in and see if that fixes it.

**Comment by maddox** [comment] 2016-09-27 20:18
@andrei4002 can try #20 and see if this works for you?

If you're unfamiliar with how to do this, just do a `git pull` on the repo to fetch the new changes, and change the branch to the `dont-stop-discovery` branch and start normally. Try to power cycle your hub and see if it:
1. doesn't crash harmoney-api
2. still controls your hub

Here's what you'll want to do.

``` sh
git-pull
git checkout dont-stop-discovery
npm start
```

**Comment by maddox** [comment] 2016-09-28 01:36
It doesn't look like any of that stuff fixes this crash. I'm working on getting if fixed in #22

**Comment by maddox** [comment] 2016-09-28 03:32
It looks like I fixed the issue with the crashing. The issue was that the `harmonyhubjs-client` lib wasn't handling certain `error` events. I've force the lib and have pointed harmony-api to use that on the `multiple-hubs` branch.

You can try using this branch for now until it's merge with `2.0` and released.

**Closed as completed** 2016-09-30 00:26 UTC
